const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Button.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Button.Acts.SetInstanceVar,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{avatars: 0},
	{Function: 0},
	{Touch: 0},
	{lbl: 0},
	{secilenAvatarlar: 0},
	{esitlsagloynArk: 0},
	{Button: 0},
	{durum: 0},
	{playBtn: 0},
	{TiledBackground: 0},
	{DragDrop: 0},
	{scnk: 0},
	{ynrge: 0},
	{girisark: 0},
	{Sine: 0},
	{oyna: 0},
	{bilg: 0},
	{nasiloyn: 0},
	{soru: 0},
	{soruTxt: 0},
	{ky: 0},
	{kx: 0},
	{secilen_islem: 0},
	{islemler: 0},
	{avatar_indeks: 0}
];

self.InstanceType = {
	avatars: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	lbl: class extends self.ITextInstance {},
	secilenAvatarlar: class extends self.IArrayInstance {},
	esitlsagloynArk: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	playBtn: class extends self.IButtonInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	scnk: class extends self.ISpriteInstance {},
	ynrge: class extends self.ISpriteInstance {},
	girisark: class extends self.ISpriteInstance {},
	oyna: class extends self.ISpriteInstance {},
	bilg: class extends self.ISpriteInstance {},
	nasiloyn: class extends self.ISpriteInstance {},
	soru: class extends self.ISpriteInstance {},
	soruTxt: class extends self.ISpriteFontInstance {}
}